### ISSUE TITLE
Iphone connectivity issue with Appium tool

### ISSUE THREAD

**Issue by qualitykiosktech** [manishPatwari/WebDriverAgent#10]
Dear Manish,
We need your help for iPhone VNC connectivity solution with Appium tool. 

Please share your contact details. If you want we will pay for solution.

**Comment by manishPatwari** [comment]
Please drop me mail with your detailed requirement @ manish.patwari06@gmail.com .

**Comment by manishPatwari** [comment]
Did hear back from you so, closing this issue. Hope it got fixed.
