### ISSUE TITLE
not support the real device

### ISSUE THREAD

**Issue by koala2012** [manishPatwari/WebDriverAgent#11]
I run command as:
xcodebuild test -workspace WebDriverAgent.xcworkspace -scheme WebDriverAgentRunner -destination "platform=iOS,id=82574ea9de567966040016e85242f1bfb4d1ab31"

I cannot get device via web portal, but I got background logs:
Test Suite 'Selected tests' started at 2018-08-26 18:36:59.744
Test Suite 'WebDriverAgentRunner.xctest' started at 2018-08-26 18:36:59.745
Test Suite 'UITestingUITests' started at 2018-08-26 18:36:59.746
Test Case '-[UITestingUITests testSocketRunner]' started.
    t =     0.00s Start Test at 2018-08-26 18:36:59.747
    t =     0.00s Set Up
2018-08-26 18:36:59.765027+0800 WebDriverAgentRunner-Runner[5088:2483869] Built at Aug 26 2018 18:36:36
2018-08-26 18:36:59.820288+0800 WebDriverAgentRunner-Runner[5088:2483920] TIC TCP Conn Failed [1:0x1c0368c40]: 1:50 Err(50)
2018-08-26 18:36:59.822727+0800 WebDriverAgentRunner-Runner[5088:2483920] Task <7EB119AF-9AEA-4434-A059-F2B878BB5C49>.<1> HTTP load failed (error code: -1009 [1:50])
2018-08-26 18:36:59.823170+0800 WebDriverAgentRunner-Runner[5088:2483889] Task <7EB119AF-9AEA-4434-A059-F2B878BB5C49>.<1> finished with error - code: -1009
2018-08-26 18:36:59.832096+0800 WebDriverAgentRunner-Runner[5088:2483920] TIC TCP Conn Failed [2:0x1c4369f00]: 1:50 Err(50)

how I can fixed ?

**Comment by manishPatwari** [comment]
Reason is "TCP Conn Failed" , You have to check your network and also make sure in the code you have correct IP address for connection.

**Comment by koala2012** [comment]
@manishPatwari where can I correct IP address. but as the same code I can get the simulator working well, why?

**Comment by manishPatwari** [comment]
Replace "localhost" in FBWebSocket.m with the ip address where Node server is running. 
Have you done this steps ?

Follow the instructions given in the repo description.

**Comment by koala2012** [comment]
yes，done this steps，but had same problem. any idea？发自我的iPhone------------------ Original ------------------From: Manish Patwari  <notifications@github.com>Date: Tue,Aug 28,2018 1:21 AMTo: manishPatwari/WebDriverAgent <WebDriverAgent@noreply.github.com>Cc: koala2012 <larrywoo1982@gmail.com>, Author <author@noreply.github.com>Subject: Re: [manishPatwari/WebDriverAgent] not support the real device (#11)Replace "localhost" in FBWebSocket.m with the ip address where Node server is running.
Have you done this steps ?
Follow the instructions given in the repo description.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/manishPatwari/WebDriverAgent","title":"manishPatwari/WebDriverAgent","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/manishPatwari/WebDriverAgent"}},"updates":{"snippets":[{"icon":"PERSON","message":"@manishPatwari in #11: Replace \"localhost\" in FBWebSocket.m with the ip address where Node server is running. \r\nHave you done this steps ?\r\n\r\nFollow the instructions given in the repo description."}],"action":{"name":"View Issue","url":"https://github.com/manishPatwari/WebDriverAgent/issues/11#issuecomment-416300559"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/manishPatwari/WebDriverAgent/issues/11#issuecomment-416300559",
"url": "https://github.com/manishPatwari/WebDriverAgent/issues/11#issuecomment-416300559",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [manishPatwari/WebDriverAgent] not support the real device (#11)",
"sections": [
{
"text": "",
"activityTitle": "**Manish Patwari**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@manishPatwari",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"manishPatwari/WebDriverAgent\",\n\"issueId\": 11,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"manishPatwari/WebDriverAgent\",\n\"issueId\": 11\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/manishPatwari/WebDriverAgent/issues/11#issuecomment-416300559"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 372464652\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by manishPatwari** [comment]
Is your mobile and the Node server are on the same network ?

**Comment by koala2012** [comment]
Do you meanby wifi network connection? Actually real device connect my Mac via USB port. Any additional connection need?发自我的iPhone------------------ Original ------------------From: Manish Patwari  <notifications@github.com>Date: Wed,Aug 29,2018 1:58 AMTo: manishPatwari/WebDriverAgent <WebDriverAgent@noreply.github.com>Cc: koala2012 <larrywoo1982@gmail.com>, Author <author@noreply.github.com>Subject: Re: [manishPatwari/WebDriverAgent] not support the real device (#11)Is your mobile and the Node server are on the same network ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/manishPatwari/WebDriverAgent","title":"manishPatwari/WebDriverAgent","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/manishPatwari/WebDriverAgent"}},"updates":{"snippets":[{"icon":"PERSON","message":"@manishPatwari in #11: Is your mobile and the Node server are on the same network ?"}],"action":{"name":"View Issue","url":"https://github.com/manishPatwari/WebDriverAgent/issues/11#issuecomment-416682545"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/manishPatwari/WebDriverAgent/issues/11#issuecomment-416682545",
"url": "https://github.com/manishPatwari/WebDriverAgent/issues/11#issuecomment-416682545",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [manishPatwari/WebDriverAgent] not support the real device (#11)",
"sections": [
{
"text": "",
"activityTitle": "**Manish Patwari**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@manishPatwari",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"manishPatwari/WebDriverAgent\",\n\"issueId\": 11,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"manishPatwari/WebDriverAgent\",\n\"issueId\": 11\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/manishPatwari/WebDriverAgent/issues/11#issuecomment-416682545"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 372464652\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by manishPatwari** [comment]
Yes,  I am talking about wifi connection. Your system where you are running Node server and the Mobile should be on the same Wifi connection., and make sure you replace the "localhost" with the Node server IP address.

**Comment by koala2012** [comment]
@manishPatwari cool, this method is working now. thanks 

one more questions: how I can make the elements inspector available? it's seems that this tool can not use.

**Comment by manishPatwari** [comment]
Currently we don't support Inspector as it slows down the refresh rate of device screen.

**Comment by koala2012** [comment]
@manishPatwari one more question, is there connection can replace Wifi connection? such as monitoring server by usb connection?
