### ISSUE TITLE
Connecting WDA via USB

### ISSUE THREAD

**Issue by SudhaChandranBC** [manishPatwari/WebDriverAgent#12]
Hi, 

I'm trying to connect device over USB. Our requirement is not to have the same network dependency.

`$ iproxy 8000 8000
waiting for connection
`

And xcode log:
`Test Case '-[UITestingUITests testSocketRunner]' started.
    t =     0.00s Start Test at 2018-09-06 11:58:40.079
    t =     0.00s Set Up
2018-09-06 11:58:40.096364+0530 WebDriverAgentRunner-Runner[303:12622] Built at Sep  6 2018 11:58:18
2018-09-06 11:58:43.146942+0530 WebDriverAgentRunner-Runner[303:12709] [] tcp_timers tcp[1] retransmit SYN 3`

I'm not getting any documentation to use the iProxy tool or usbmux tool.

**Comment by SudhaChandranBC** [comment]
Hi, I have connected the device through USB. Server started and the client connected.
I installed WDA into iPhone, still, iPhone not listed in connected devices. It says No Devices Connected.

**Comment by manishPatwari** [comment]
Currently device and the node server should on the same network for working as device lab. USB connection is not yet supported. Love to accept this feature as PR.
