### ISSUE TITLE
Remote Control iOS device -  Not work with Appium

### ISSUE THREAD

**Issue by Tanajimandhare** [manishPatwari/WebDriverAgent#6]
The WebDriverAgent version available at “https://github.com/manishPatwari/WebDriverAgent” works fine when we run it alone. 
But on starting Appium script execution, Appium/ADB also start their own WebDriverAgent instance and as it finds another instance already running, it kills it.  

Need your help , How we can run WebDriverAgent with Appium/ ADB at a time. 

Regards
Tanaji Mandhare 
8898113355

**Comment by Tanajimandhare** [comment]
Dear Team,

Waiting for your help.

**Comment by manishPatwari** [comment]
What is the use case for you to run Appium script with the WebDriverAgent for remote device?

 “https://github.com/manishPatwari/WebDriverAgent”  its for solving remote access of the device.
